### ISSUE TITLE
How to run SRWM on a CPU?

### ISSUE THREAD

**Issue by Augus1999** [IDSIA/modern-srwm#1]
I found `SRWMlayer` requires CUDA installed. My local machine has no GPUs and if I try to run these codes, it raises
```bash
raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```
Could you provide some advice about how to modify it to run on a CPU?

**Comment by kazuki-irie** [comment]
Thank you for your interest!

Unfortunately, there is no CPU version of SRWM implemented (you can not just modify the existing code to support CPUs).
Unless you have some specific use case in mind (e.g., training on a GPU but evaluation on CPUs), it is in general not a good idea to run these models on CPUs (that would be very slow).

If you wish, I can still add a simple/pure PyTorch implementation of the SRWM layer (which can be run on a CPU). But that will be so slow that it may be not useful at all in practice.

**Comment by Augus1999** [comment]
Thanks for your reply!

Yes I plan to evaluate on CPUs after training. I will be grateful if you can provide a prue pytorch implementation. 
Thanks a lot!
